<?php

namespace App\Models\Enums;

use OpenApi\Attributes as OA;

#[OA\Schema(
    title: 'BodyType',
    type: 'string',
    enum: [
        'O_BLUE_WHITE_STAR',

        'B_BLUE_WHITE_STAR',
        'B_BLUE_WHITE_SUPER_GIANT_STAR',

        'A_BLUE_WHITE_STAR',
        'A_BLUE_WHITE_SUPER_GIANT_STAR',

        'F_WHITE_STAR',
        'F_WHITE_SUPER_GIANT_STAR',

        'G_WHITE_YELLOW_STAR',
        'G_WHITE_YELLOW_SUPER_GIANT_STAR',

        'K_YELLOW_ORANGE_STAR',
        'K_YELLOW_ORANGE_GIANT_STAR',

        'M_RED_DWARF_STAR',
        'M_RED_DWARF_GIANT_STAR',
        'M_RED_DWARF_SUPER_GIANT_STAR',

        'L_BROWN_DWARF_STAR',
        'T_BROWN_DWARF_STAR',
        'Y_BROWN_DWARF_STAR',

        'T_TAURI_STAR',

        'AE_AB_STAR',

        'W_STAR',
        'WN_STAR',
        'WNC_STAR',
        'WC_STAR',
        'WO_STAR',

        'CS_STAR',
        'C_STAR',
        'CN_STAR',
        'CJ_STAR',
        'CH_STAR',
        'CHD_STAR',

        'MS_STAR',
        'S_STAR',

        'D_WHITE_DWARF_STAR',
        'DA_WHITE_DWARF_STAR',
        'DAB_WHITE_DWARF_STAR',
        'DAO_WHITE_DWARF_STAR',
        'DAZ_WHITE_DWARF_STAR',
        'DAV_WHITE_DWARF_STAR',
        'DB_WHITE_DWARF_STAR',
        'DBZ_WHITE_DWARF_STAR',
        'DBV_WHITE_DWARF_STAR',
        'DO_WHITE_DWARF_STAR',
        'DOV_WHITE_DWARF_STAR',
        'DQ_WHITE_DWARF_STAR',
        'DC_WHITE_DWARF_STAR',
        'DCV_WHITE_DWARF_STAR',
        'DX_WHITE_DWARF_STAR',

        'NEUTRON_STAR',

        'BLACK_HOLE',

        'X_EXOTIC_STAR',

        'SUPER_MASSIVE_BLACKHOLE',

        'ROGUE_PLANET',

        'NEBULA',

        'STELLAR_REMNANT_NEBULAR',

        // Planet types
        'METAL_RICH_BODY',
        'HIGH_METAL_CONTENT_BODY',
        'ROCKY_BODY',
        'ICY_BODY',
        'ROCKY_ICY_BODY',
        'EARTHLIKE_BODY',
        'WATER_WORLD',
        'AMMONIA_WORLD',
        'WATER_GIANT',
        'WATER_GIANT_WITH_LIFE',
        'GAS_GIANT_WITH_WATER_BASED_LIFE',
        'GAS_GIANT_WITH_AMMONIA_BASED_LIFE',
        'SUDARSKY_CLASS_I_GAS_GIANT',
        'SUDARSKY_CLASS_II_GAS_GIANT',
        'SUDARSKY_CLASS_III_GAS_GIANT',
        'SUDARSKY_CLASS_IV_GAS_GIANT',
        'SUDARSKY_CLASS_V_GAS_GIANT',
        'HELIUM_RICH_GAS_GIANT',
        'HELIUM_GAS_GIANT'
    ]
)]
enum BodyType: String {


// Star types
case O_BLUE_WHITE_STAR = 'O_BLUE_WHITE_STAR';

case B_BLUE_WHITE_STAR = 'B_BLUE_WHITE_STAR';
case B_BLUE_WHITE_SUPER_GIANT_STAR = 'B_BLUE_WHITE_SUPER_GIANT_STAR';

case A_BLUE_WHITE_STAR = 'A_BLUE_WHITE_STAR';
case A_BLUE_WHITE_SUPER_GIANT_STAR = 'A_BLUE_WHITE_SUPER_GIANT_STAR';

case F_WHITE_STAR = 'F_WHITE_STAR';
case F_WHITE_SUPER_GIANT_STAR = 'F_WHITE_SUPER_GIANT_STAR';

case G_WHITE_YELLOW_STAR = 'G_WHITE_YELLOW_STAR';
case G_WHITE_YELLOW_SUPER_GIANT_STAR = 'G_WHITE_YELLOW_SUPER_GIANT_STAR';

case K_YELLOW_ORANGE_STAR = 'K_YELLOW_ORANGE_STAR';
case K_YELLOW_ORANGE_GIANT_STAR = 'K_YELLOW_ORANGE_GIANT_STAR';

case M_RED_DWARF_STAR = 'M_RED_DWARF_STAR';
case M_RED_DWARF_GIANT_STAR = 'M_RED_DWARF_GIANT_STAR';
case M_RED_DWARF_SUPER_GIANT_STAR = 'M_RED_DWARF_SUPER_GIANT_STAR';

case L_BROWN_DWARF_STAR = 'L_BROWN_DWARF_STAR';

case T_BROWN_DWARF_STAR = 'T_BROWN_DWARF_STAR';

case Y_BROWN_DWARF_STAR = 'Y_BROWN_DWARF_STAR';

case T_TAURI_STAR = 'T_TAURI_STAR';

case AE_AB_STAR = 'AE_AB_STAR';

case W_STAR = 'W_STAR';
case WN_STAR = 'WN_STAR';
case WNC_STAR = 'WNC_STAR';
case WC_STAR = 'WC_STAR';
case WO_STAR = 'WO_STAR';

case CS_STAR = 'CS_STAR';
case C_STAR = 'C_STAR';
case CN_STAR = 'CN_STAR';
case CJ_STAR = 'CJ_STAR';
case CH_STAR = 'CH_STAR';
case CHD_STAR = 'CHD_STAR';

case MS_STAR = 'MS_STAR';
case S_STAR = 'S_STAR';

case D_WHITE_DWARF_STAR = 'D_WHITE_DWARF_STAR';
case DA_WHITE_DWARF_STAR = 'DA_WHITE_DWARF_STAR';
case DAB_WHITE_DWARF_STAR = 'DAB_WHITE_DWARF_STAR';
case DAO_WHITE_DWARF_STAR = 'DAO_WHITE_DWARF_STAR';
case DAZ_WHITE_DWARF_STAR = 'DAZ_WHITE_DWARF_STAR';
case DAV_WHITE_DWARF_STAR = 'DAV_WHITE_DWARF_STAR';
case DB_WHITE_DWARF_STAR = 'DB_WHITE_DWARF_STAR';
case DBZ_WHITE_DWARF_STAR = 'DBZ_WHITE_DWARF_STAR';
case DBV_WHITE_DWARF_STAR = 'DBV_WHITE_DWARF_STAR';
case DO_WHITE_DWARF_STAR = 'DO_WHITE_DWARF_STAR';
case DOV_WHITE_DWARF_STAR = 'DOV_WHITE_DWARF_STAR';
case DQ_WHITE_DWARF_STAR = 'DQ_WHITE_DWARF_STAR';
case DC_WHITE_DWARF_STAR = 'DC_WHITE_DWARF_STAR';
case DCV_WHITE_DWARF_STAR = 'DCV_WHITE_DWARF_STAR';
case DX_WHITE_DWARF_STAR = 'DX_WHITE_DWARF_STAR';

case NEUTRON_STAR = 'NEUTRON_STAR';

case BLACK_HOLE = 'BLACK_HOLE';

case X_EXOTIC_STAR = 'X_EXOTIC_STAR';

case SUPER_MASSIVE_BLACKHOLE = 'SUPER_MASSIVE_BLACKHOLE';

case ROGUE_PLANET = 'ROGUE_PLANET';

case NEBULA = 'NEBULA';

case STELLAR_REMNANT_NEBULAR = 'STELLAR_REMNANT_NEBULAR';


/* Planet types */
case METAL_RICH_BODY = 'METAL_RICH_BODY';
case HIGH_METAL_CONTENT_BODY = 'HIGH_METAL_CONTENT_BODY';
case ROCKY_BODY = 'ROCKY_BODY';
case ICY_BODY = 'ICY_BODY';
case ROCKY_ICY_BODY = 'ROCKY_ICY_BODY';
case EARTHLIKE_BODY = 'EARTHLIKE_BODY';
case WATER_WORLD = 'WATER_WORLD';
case AMMONIA_WORLD = 'AMMONIA_WORLD';
case WATER_GIANT = 'WATER_GIANT';
case WATER_GIANT_WITH_LIFE = 'WATER_GIANT_WITH_LIFE';
case GAS_GIANT_WITH_WATER_BASED_LIFE = 'GAS_GIANT_WITH_WATER_BASED_LIFE';
case GAS_GIANT_WITH_AMMONIA_BASED_LIFE = 'GAS_GIANT_WITH_AMMONIA_BASED_LIFE';
case SUDARSKY_CLASS_I_GAS_GIANT = 'SUDARSKY_CLASS_I_GAS_GIANT';
case SUDARSKY_CLASS_II_GAS_GIANT = 'SUDARSKY_CLASS_II_GAS_GIANT';
case SUDARSKY_CLASS_III_GAS_GIANT = 'SUDARSKY_CLASS_III_GAS_GIANT';
case SUDARSKY_CLASS_IV_GAS_GIANT = 'SUDARSKY_CLASS_IV_GAS_GIANT';
case SUDARSKY_CLASS_V_GAS_GIANT = 'SUDARSKY_CLASS_V_GAS_GIANT';
case HELIUM_RICH_GAS_GIANT = 'HELIUM_RICH_GAS_GIANT';
case HELIUM_GAS_GIANT = 'HELIUM_GAS_GIANT';

}
